name: Backend CI/CD

on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: echo "No tests yet"

      - name: Start server check
        run: |
          NODE_ENV=test timeout 5s node ./bin/www
          EXIT_CODE=$?
          echo "Exit code: $EXIT_CODE"

          if [ $EXIT_CODE -ne 0 ] && [ $EXIT_CODE -ne 124 ]; then
            exit $EXIT_CODE
          fi

          echo "Server check passed"

      - name: Trigger Render Deploy
        if: success() # ✅ only deploy if CI passed
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
