name: Backend CI/CD

on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: echo "No tests yet"

      - name: Start server check
        run: |
          NODE_ENV=test timeout 5s node ./bin/www
          EXIT_CODE=$?
          if [ $EXIT_CODE -ne 124 ]; then exit $EXIT_CODE; fi

      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
